### ISSUE TITLE
Ansible Bot, Ansible Bot, Ansible Bot, I summon thee

### ISSUE THREAD

**Issue by mpdehaan** [jctanner/issuetests#8]
Oh hai!  I'm commenting above the ticket just to be sneaky.
##### Issue Type:

What kind of ticket is this?  It's a Bug Report.
##### Ansible Version:

Please supply the verbatim output from running “ansible --version”.   ansible --version
##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.07, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”. 

NA
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.

Here I am commenting below the line
##### Steps To Reproduce:

Here I am commenting above the line

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is neccessary, please link one uploaded to gist.github.com. 
##### Expected Results:

I am in your white space

Please enter your expected results in this space.  When running the steps supplied above, what would you expect to happen?  If showing example output, indent your output by four spaces so it will render correctly in GitHub. 
and below
##### Actual Results: Not following instructions

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If showing example output, indent your output by four spaces so it will render correctly in GitHub.

**Comment by jctanner** [comment]
This issue was moved to jctanner/issuetests2#4
